language: php

branches:
  - master

php:
  - '5.5'
  - '7.0'
  - '7.1'

install:
  - sudo apt-get install -qq --force-yes beanstalkd
  - pecl install swoole
  - composer install

script: 
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache
