language: php

branches:
  - master

php:
  - '5.5'
  - '7.0'
  - '7.1'

install:
  - pecl install swoole
  - composer install

script: 
  - phpunit

cache:
  directories:
    - $HOME/.composer/cache
